name: data_extractor
description: A data extractor for pdf files & web pages
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  dartz: ^0.10.1
  device_preview: ^1.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.3
  file_picker: ^5.0.1
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.3
  formz: ^0.4.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  pdf_text: ^0.5.0
  pdfx: ^2.2.0
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  syncfusion_flutter_pdf: ^20.2.44


dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
